name: Global IP Factory
on:
  schedule:
    - cron: '0 4 * * *' # 每天北京时间 12:00 运行
  workflow_dispatch: # 支持你手动点一下运行

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Factory
        run: python collect.py

      - name: Commit and Push
        run: |
          git config --global user.name "IP-Bot"
          git config --global user.email "bot@github.com"
          git add all.txt
          git commit -m "Update IPs $(date)" || exit 0
          git push
